sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  wechat:
    appid: wx590415d253dbf081
    secret: 996c3d0d55d9986a76022ce2a809520e


  redis:
    host: localhost
    port: 6379

    database: 10


